const actionTypes = {
    USER_LOGIN: 'USER_LOGIN',
    IS_USER_LOGGED: 'IS_USER_LOGGED',
    SPELLS_FETCHED: 'SPELLS_FETCHED',
    
    SPELL_CREATE: 'SPELL_CREATE',
    SPELL_VIEW: 'SPELL_VIEW',
    SPELL_EDIT: 'SPELL_EDIT',
    SPELL_DELETE: 'SPELL_DELETE',
    
    TEMP: 'TEMP',
}

export default actionTypes;